### ISSUE TITLE
update docu regarding to deferred dispatches in core

### ISSUE THREAD

**Issue by torsten-knauf** [FACT-Finder-Web-Components/documentation#106]
I think our deferred dispatches starting with version 1.2.12 should be mentioned in _Ready Events_-Section as shown in screenshot below

![updatedocu](https://user-images.githubusercontent.com/42941766/46725068-a8cf4600-cc7b-11e8-85d6-0173679fd64b.png)

**Comment by torsten-knauf** [comment]
Put on hold due to FFWEB-925, which maybe will even made this deferment unnecessary

**Comment by damrath** [comment]
@torsten-knauf is this still relevant?

**Comment by torsten-knauf** [comment]
Cause of internal LitElement migration, this will needs some time. So please update to current status
