### ISSUE TITLE
Unify vocabulary

### ISSUE THREAD

**Issue by torsten-knauf** [FACT-Finder-Web-Components/documentation#109]
Speak consistently of _our Web Components_ instead of _custom elements_ in the docu [as pointed out here](https://github.com/FACT-Finder-Web-Components/documentation/pull/105#discussion_r224099036)

**Comment by torsten-knauf** [comment]
also unify:
- "url" or "URL"
- "a HTML" or "an HTML"

**Comment by torsten-knauf** [comment]
Because _Web Components_ is an official term and it is really confusing to read something in our documentation like _We strongly suggest to use the latest version of Web Components_, we decided today in daily  to call our Web Components **Fact Finder Web Components**. Hence we should consistently speak of **Fact Finder Web Components**, when we mean our Components :)

**Comment by damrath** [comment]
@torsten-knauf 
i created #121 a separate issue for this as this requires going through every mention of web components and similar terms and making a context-based decision for the naming, which was not the aim of this current issue.

**Comment by damrath** [comment]
Well i don't agree with this. If the goal of the documentation is to help developers understand our product / API, then we should use clear and concise language. It's not advantageous to slap our brand in front of every occurrence of the term *Web Components*. The goal of this issue was to remove ambiguity (custom elements vs. web components) not to introduce bloat.

**Comment by torsten-knauf** [comment]
In my opinion just writing _Web Components_ is wrong, because that is a name for a set of web features. On the other side I think _FACT-Finder Web Components_ is not only correct but it also helps to not add further confusion to the term of Web Components and Custom Elements.

@toarm I think it would be nice to have a final decision how to do it. Just decide something, or start a quick vote within this issue pls :) You could write all versions you think are acceptable in a custom comment and we give our likes to them as a vote.

**Comment by torsten-knauf** [comment]
as far as I remember _our *_ wasn't liked by @omikron-fp. As I original suggested, I would still be fine with something like _our components_

> Please re-read my comment. I was not proposing using the term `custom elements`.

Me neither :)

**Comment by damrath** [comment]
> Me neither :)
I didn't think so. :+1: 

Well, i can see `our components` specifically being a suboptimal solution.

I'm gonna stick to: `FACT-Finder Web Components` for the most part and just try and rephrase paragraphs that use the term too often. I think that should cover 98% of cases.
