### ISSUE TITLE
Purge legacy files

### ISSUE THREAD

**Issue by damrath** [FACT-Finder-Web-Components/documentation#123]
Apparently some files aren't used in the actual documentation but still float around in the directory. They should be purged. 

_Originally posted by @omikron-fp in https://github.com/FACT-Finder-Web-Components/documentation/pull/122_

**Comment by omikron-fp** [comment]
[api.js](https://github.com/FACT-Finder-Web-Components/documentation/blob/master/src/data/api.js) has redirects configured for when these obsolete pages are navigated to.
Having the physical, yet obsolete, files may be a good reminder of which old pages you want to configure a redirect for. But perhaps it's enough to drop another comment in api.js to avoid accidental removal of the redirects. At least until we decide to no longer support navigating to obsolete pages.

**Comment by damrath** [comment]
I think keeping the obsolete physical files is not a very good idea. Sometimes i have to go through all files to replace links or change certain keywords and having files in there that aren't really used just makes this process unnecessarily long.

Dropping a comment in `api.js` with the commit-hash or a link to the PR in which these files were removed and explaining the rationale for their removal would be my solution. What do you think?

**Comment by omikron-fp** [comment]
Sounds perfectly fine to me.
I can't tell though if someone else has any objection to removing them. I guess not. And if the relevant PR/commit is mentioned, it should be easy enough to restore them.
