### ISSUE TITLE
Consistent use of quotes

### ISSUE THREAD

**Issue by damrath** [FACT-Finder-Web-Components/documentation#128]
>Are we actually using single/double-quotes consistently in the documentation?

_Originally posted by @omikron-fp in https://github.com/FACT-Finder-Web-Components/documentation/pull/127_
@toarm 

We need to decide which types of quotes we want to use and make it uniform across the entire documentation.

**Comment by damrath** [comment]
Obviously we need the double quotes for HTML attributes, but other than that i'd prefer single quotes.

Any other opinions?

**Comment by omikron-fp** [comment]
Let's use backticks as we are in our internal projects.
Where backticks aren't allowed I'd go for double-quotes. Like pretty much any programming language in the world does. And the JSON standard as well.

**Comment by toarm** [comment]
we already agreed on backticks.
