### ISSUE TITLE
404 in suggest demo

### ISSUE THREAD

**Issue by damrath** [FACT-Finder-Web-Components/documentation#176]
#### Current behaviour

The [3.x suggest-demo](https://web-components.fact-finder.de/api/3.x/ff-suggest#tab=demo) returns a 404.

#### Expected Behaviour

Working demo

**Comment by omikron-fp** [comment]
Temporarily fixed by adjusting directories on the server.
We still need to consider a fix that lasts beyond the next deployment of the demos.
Could be creating a demo in a directory that matches the requested path from the docs or even a mapping that allows targeting arbitrary URLs as demo.

**Comment by omikron-fp** [comment]
Added `ff-suggest` demos for `1.x` and `3.x` to _demos_ project. Deployment should now be a simple copy&paste task.
