### ISSUE TITLE
Proofread documentation

### ISSUE THREAD

**Issue by omikron-fp** [FACT-Finder-Web-Components/documentation#33]
Several pages of the documentation contain grammatical errors, TODOs, copy/paste-errors etc.
Would probably be best to double-check all pages.

**Comment by torsten-knauf** [comment]
In https://web-components.fact-finder.de/api/ff-searchbox#tab=docs the link within "API reference" is broken. The real target is probably https://web-components.fact-finder.de/api/ff-searchbox#tab=api

**Comment by torsten-knauf** [comment]
repeated "not" on https://web-components.fact-finder.de/api/core-event-aggregator#tab=docs in "NOTE: Each property which is not not a function or an object is translated to an http request parameter with a few exceptions:"

**Comment by torsten-knauf** [comment]
link to "Suggest Example. " on https://web-components.fact-finder.de/api/ff-searchbox#tab=docs is broken

**Comment by torsten-knauf** [comment]
![glitch in der matrix](https://user-images.githubusercontent.com/42941766/45428336-4cd7c880-b6a1-11e8-83ff-bb37becfa7ce.png)

**Comment by torsten-knauf** [comment]
tpoic _singleWordSearch_ occurs twice in topic listing at https://web-components.fact-finder.de/api/core-result-dispatcher#tab=docs

**Comment by torsten-knauf** [comment]
on https://web-components.fact-finder.de/documentation/tracking-guide "<br> <br>" is probably an accident of markup mismatch?

**Comment by torsten-knauf** [comment]
typo in _hide-e**pm**ty-groups_ in https://web-components.fact-finder.de/api/ff-header-navigation#tab=api (attribute is correctly called "hideEmptyGroups" in src-code)

**Comment by damrath** [comment]
> linkt to " ff-slider-control" on [web-components.fact-finder.de/api/ff-asn#tab=docs](https://web-components.fact-finder.de/api/ff-asn#tab=docs) is broken

Can't be fixed as long as we use the `#tab=doc`

**Comment by torsten-knauf** [comment]
on https://web-components.fact-finder.de/documentation/install-dist fst line:

"Depending on whether you are using the Node.js you have the following ~~to~~ two ways of installing Web Components."

**Comment by torsten-knauf** [comment]
In https://web-components.fact-finder.de/documentation/communication

So basically all you need to do is strip everything before the API-Name away and replace it by the original FACT-Finder URL. Taking the URLs from Step ~~1.~~ one the **url changes** would **be** like:

So basically all you need to do is strip everything before the API-Name away and replace it by the original FACT-Finder URL. Taking the URLs from Step one the changed URLs would be like:

**Comment by torsten-knauf** [comment]
In https://web-components.fact-finder.de/api/core-event-aggregator there is one "Fact-Finder". But everywhere else it is "FACT-Finder"

**Comment by omikron-fp** [comment]
Sufficiently done. And old.
