### ISSUE TITLE
Search results contain old URLs

### ISSUE THREAD

**Issue by KrzysztofKozlowskiOBSS** [FACT-Finder-Web-Components/documentation#42]
#### Current behaviour

Clicks on search results are redirecting to old URLs.

#### Expected Behaviour

New URLs are served.

We have to import updated feed in FF.

**Comment by damrath** [comment]
Due to the changes in the file/dir structure of the documentation project, the export  code will have to be changed.
we might as well consider a "re-write" to turn it into a REST-API that the FF can query regularly.

**Comment by toarm** [comment]
remove the search icon until we've fixed it.

**Comment by damrath** [comment]
FF-Database was updated in #45 so this issue is fixed
