### ISSUE TITLE
change webcomponents polyfill for npm

### ISSUE THREAD

**Issue by torsten-knauf** [FACT-Finder-Web-Components/documentation#63]
#### Current behaviour

```npm install ff-web-components``` is unable to resolve the dependency _"webcomponentsjs": "git://github.com/webcomponents/webcomponentsjs.git#v0.7.24"_ from  ff-web-components itself, which is needed as polyfill for some browsers. Replacing it through the real npm module _"webcomponents.js": "^0.7.24"_  should fix it, I guess.

When using npm, a hint for the boilerplate to change the related links might be nice as well, although it is fairly self-explanatory.

```
    <script src="../node_modules/webcomponents.js/webcomponents-lite.min.js"></script>
    <link rel="import" href="../node_modules/ff-web-components/dist/elements.build_with_dependencies.html">
```

**Comment by damrath** [comment]
Not related to documentation => moved to internal JIRA
