### ISSUE TITLE
update latest download version on homepage

### ISSUE THREAD

**Issue by torsten-knauf** [FACT-Finder-Web-Components/documentation#96]
The lates version of ff-web-components on the [download page](https://web-components.fact-finder.de/download) is 1.2.9. The latest version as well as the default select version should be 1.2.11

**Comment by torsten-knauf** [comment]
waiting for internal ticket regarding automatic sync of versions and download possibilities

**Comment by damrath** [comment]
this was ninja fixed in https://github.com/FACT-Finder-Web-Components/documentation/commit/e1ab1bfd759f5877074f27dab28bf93e315df401
